apiVersion: snapshot.wbc.com/v1alpha1
kind: WbcSnapshot
metadata:
  labels:
    app.kubernetes.io/name: wbcsnapshot
    app.kubernetes.io/instance: wbcsnapshot-sample
    app.kubernetes.io/part-of: testvm
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: testvm
  name: wbcsnapshot-sample
spec:
  # TODO(user): Add fields here
